### ISSUE TITLE
unable to locate bluealsa?

### ISSUE THREAD

**Issue by abuonline** [nicokaiser/rpi-audio-receiver#1]
when i do sudo ./install-bluetooth.sh "E: unable to locate packgae bluealsa"  appeared. Maybe u can add like repository first for bluealsa?

**Comment by nicokaiser** [comment]
Did you do `apt update` before?

**Comment by nicokaiser** [comment]
Please try again with updated packages. When runing `apt update` before, the package should be found and installed.
