### ISSUE TITLE
Some problems on RPi3B

### ISSUE THREAD

**Issue by prsolucoes** [nicokaiser/rpi-audio-receiver#11]
Hi,

Some problems when i execute your scripts:

- only android devices can be paired.
- after paired with android devices, the audio don't output to rpi3.
- iphone bluetooth devices don't list raspberry.

Thanks.

**Comment by nicokaiser** [comment]
What kind of Bluetooth device are you using? The Bluetooth capabilities of the Rasbperry Pi is very limited, so it is recommended to use an external USB Bluetooth stick.
