### ISSUE TITLE
File enable-read-only.sh not present

### ISSUE THREAD

**Issue by pililac** [nicokaiser/rpi-audio-receiver#114]
The file called in line 46 in install.sh is not present.

https://github.com/nicokaiser/rpi-audio-receiver/blob/6fc2984d1dd206972d935b54c3446a4019f946bc/install.sh#L46

**Comment by psiberfunk** [comment]
+1 , same problem for me.

**Comment by nicokaiser** [comment]
Good catch, fixed in be79573.
