### ISSUE TITLE
Bluetooth authentification does not work after completely disconnect and reconnect

### ISSUE THREAD

**Issue by manuelambaum** [nicokaiser/rpi-audio-receiver#119]
Hi, i have the same issue as discussed in the previous post: https://github.com/nicokaiser/rpi-audio-receiver/issues/99
If i completely disconnect the bluetooth connection from my phone/laptop to the raspberry pi, the is the error with wrong pin or password. I think i installed the newest version of this library, but it semms that it does not work. Can anyone help me? thanks

**Comment by nicokaiser** [comment]
This is strange, you should never need to enter a PIN or password. I’ll have a look at it next week.

**Comment by arxeiss** [comment]
Maybe not related, but I also have to enter PIN. But not with new Bluetooth USB dongle.
This is what I did from the beginning:
