### ISSUE TITLE
hdmi audio not working at all with 2021-05-07-raspios-buster-armhf-lite

### ISSUE THREAD

**Issue by No3ight** [nicokaiser/rpi-audio-receiver#128]
I´ve installed your work on a completely fresh installation of "buster lite". HDMI wont work at all. Even in raspi-config there is no option to select under audio-settings. 

I´ve also tried many suggestions from similar threads. Nothing. Headphone jack seems to work out of the box but in horrible quality. Same on my second rpi.

Is there a workaround? Acutally installing the desktop version and will report to you.

Thanks in advance.

**Comment by nicokaiser** [comment]
Did HDMI audio work on a clean Buster Installation, and before installing this script?
