### ISSUE TITLE
bluetooth-udev doesn't seem to execute at all

### ISSUE THREAD

**Issue by Panaphobe** [nicokaiser/rpi-audio-receiver#132]
Running rpi-audio-receiver on a Pi Zero 2 for a headless application and thought I would test to see if its bluetooth chip is acceptable on its own or whether I'd need a dongle.

I uncommented both ifconfig lines in bluetooth-udev, but the wifi doesn't toggle when I connect/disconnect a bluetooth device. To troubleshoot this I tried adding the device-added and device-removed aplay commands to their respective if sections. The sounds don't work either, so it seems as if the bluetooth-udev isn't running at all for some reason.

I also tried uncommenting the first line of the file, which had no effect so I re-commented it.
Finally I tried manually running the ifconfig lines on their own in a terminal, and got an error: "SIOCSIFFLAGS: Operation not permitted". The ifconfig lines run fine in a terminal if preceded by sudo, and adding sudo to the appropriate lines inside bluetooth-udev has no effect.

It seems like maybe bluetooth-udev might be failing to do anything because it is not running with appropriate permissions? Thanks for any help.

Full content of my bluetooth-udev (hopefully without errors, it's manually typed out here as I don't have an easy way to transfer the file to the PC I'm making this issue report from):
#!/bin/bash

if [[ ! $NAME =~ ^/"([0-9A-F]{2}[:-]){5}(0-9A-F{2})\"$ ]]; then exit 0; fi

action=$(expr "$ACTION" : "\([a-zA-Z]\+\).*")

if [ "$action" = "add" ]; then
    bluetoothctl discoverable off
    # disconnect wifi to prevent dropouts
    ifconfig wlan0 down &
    aplay -q /usr/local/share/sounds/__custom/device-added.wav
fi

if [ "$action" = "remove" ]; then
    # reenable wifi
    ifconfig wlan0 up &
    bluetoothctl discoverable on
    aplay -q /usr/local/share/sounds/__custom/device-removed.wav
fi

**Comment by sebastian-de** [comment]
I also noticed that commands in `/usr/local/bin/bluetooth-udev` didn't execute. I want to run `mpc stop` in case my MPD server is currently playing something, but playback didn't stop upon connecting a bluetooth device.

For me removing/commenting the `NAME` condition did the trick:
https://github.com/nicokaiser/rpi-audio-receiver/blob/2b7ef54b21c4764a53e90e7cf1eedf1dbe48e7a2/install-bluetooth.sh#L60

Now all commands get executed upon a bluetooth connect.
I'm using the RP4 built-in bluetooth (yes, I'm aware of the downsides).
