### ISSUE TITLE
UPnP Support

### ISSUE THREAD

**Issue by Butzlabben** [nicokaiser/rpi-audio-receiver#134]
Hi,

the project description and readme say, that upnp would be supported. But commit [06129ca](https://github.com/nicokaiser/rpi-audio-receiver/commit/06129cafafb661d5256488201ecdbbebef8d4fbb) removed support for upnp. Would it be possible to add upnp support again with [gmrender-resurrect](https://github.com/hzeller/gmrender-resurrect/)?

**Comment by nicokaiser** [comment]
Sorry, I cannot support UPnP configurations anymore, since I am not using it at all. You can try installing `gmediarender` and its dependencies and see if you get it working, but I cannot provide an installation script for this.

**Comment by Butzlabben** [comment]
Hi,

I got it working with the mentioned github repository. I could provide an install script for upnp, if you want.
