### ISSUE TITLE
Installation script for raspberry pi zero w 1.x

### ISSUE THREAD

**Issue by Arcadia197** [nicokaiser/rpi-audio-receiver#135]
Together with Debian 11 not containing BlueAlsa and breaking changes within Librespot to no longer continue support for ARMv6, the current version of the script does not work for the raspberry pi zero w 1.x.

I have therefore assembled the last working versions still running on a RPi zero. This works on Debian 10 Buster (legacy) with the old bluetooth-script together with the last compatible version of Raspotify.

You can find everything together in [my fork](https://github.com/Arcadia197/rpi-audio-receiver) which I have created. I thought you might be interested to include this somewhere. I am using it on three RPi zero w and it is working fine for now. This might especially be useful as it is currently hard to get a hold on a new RPi zero w 2.x.

**Comment by nicokaiser** [comment]
Thank you! I added a link to your fork to README.md
