### ISSUE TITLE
Bluetooth connection request spams

### ISSUE THREAD

**Issue by gherucuBitz** [nicokaiser/rpi-audio-receiver#136]
Everytime I turn on my bluetooth on my laptop, I get spammed by connection requests from the raspberry pi even if I am connected or not. It still works though but I get spammed heavily by that. Although, this does not happen on my iPhone (don’t know if it can happen)

my laptop runs macos and in the beginning this strange thing did not happen and I don t see any control panel or anything similar for this tool. 

I want to mention that other than this (and even with this) it is an amazing software and I am very pleased congrats bro!

**Comment by nicokaiser** [comment]
This is strange a BlueZ device should not try to connect to other devices by themselves. Are you sure you use the default config and nothing else on the Pi? Maybe it is just broadcasting its name (which is fine)?
