### ISSUE TITLE
Delay/latency when streaming bluetooth audio (especially from Mac)

### ISSUE THREAD

**Issue by andreiciceu** [nicokaiser/rpi-audio-receiver#138]
Firstly thanks for this great library, it's amazingly simple to use.

I noticed there's a slight delay(lag) between the source (Macbook) and the output (speakers), ~0.7s. It's especially noticeable when playing youtube videos.
Streaming from Android phone seems to have less latency (~0.2s)

It happens randomly, sometimes after i disconnect/reconnect it works ok (when both devices are connected).

Do you have any idea why and how this could be fixed?

--
Model		: Raspberry Pi 4 Model B Rev 1.1

**Comment by nicokaiser** [comment]
I think there is nothing that can be done about this, it seems to be an inherent character of Bluetooth audio connections. When using a Mac, you are much much better off just using AirPlay – the audio quality is much better, and the latency is compensated automatically.
