### ISSUE TITLE
Also device settings

### ISSUE THREAD

**Issue by pla10** [nicokaiser/rpi-audio-receiver#139]
How should I do to set the wanted alsa device to output the audio received from Bluetooth?
In my case I would like to set it to a loopback, since that's what I use for snapcast (already works with spotify connect and airplay)

**Comment by nicokaiser** [comment]
You need to configure PulseAudio to use a specific ALSA output device. I don't really know how this works, but maybe this helps: https://wiki.archlinux.org/title/PulseAudio/Examples#Set_the_default_output_sink 

BTW, Spotify Connect and AirPlay _should_ also send audio through PulseAudio (not ALSA directly) to avoid concurrency and locking problems.
