### ISSUE TITLE
Is there a way to do this with buildroot with other DACs besides hifiberry?

### ISSUE THREAD

**Issue by thebestofall007** [nicokaiser/rpi-audio-receiver#140]
Title says it. I was able to get the rpi receiver to work with the flatmax audioinjector stereo DAC using the instructions you provided. The main problem I have is that the raspberry pi OS, even the lite version, takes too long to boot on my raspberry pi b+.

**Comment by nicokaiser** [comment]
Sorry, I cannot support buildroot systems at this point. This project is very much centered around Raspbian (Raspberry Pi OS) and its packages and configs, buildroot has some very different approaches in quite some areas.

With a small (!) SD card and some tweaking it boots reasonably fast even on a Raspberry Pi 1, but you are right, it will never come near the startup speed of a very customized buildroot system.

You might want to try HiFiBerry OS, it is based on buildroot and has very good audio features and DAC support.
