### ISSUE TITLE
Debian 10 installation stops on Spotify Connect, because of bullseye packages requirements 

### ISSUE THREAD

**Issue by Orestos** [nicokaiser/rpi-audio-receiver#143]
Installation stops on Spotify connect and want bullseye packages (i think it's not possible to install it on buster)

> Do you want to install Spotify Connect (Raspotify)? [y/N] Y
> 
> Unmet minimum required package version(s):
> 
> libc6 >= 2.31 is required but 2.28-10+rpt2+rpi1+deb10u1 is installed.
> systemd >= 247.3 is required but 241-7 deb10u8+rpi1 is installed.
> libasound2 >= 1.2.4 is required but 1.1.8-1+rpt2 is installed.
> alsa-utils >= 1.2.4 is required but 1.1.8-2+rpt1 is installed.
> libpulse0 >= 14.2 is required but 12.2-4+deb10u1+rpt3 is installed.
> Please make sure you are running a compatible armhf (ARMv7), arm64, or amd64 Debian based OS.
> pi@soundbarPi4: /rpi-audio-receiver-debian-10 $ cat /etc/os-releasePRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
> NAME="Raspbian GNU/Linux"
> VERSION_ID="10"
> VERSION="10 (buster)"
> VERSION_CODENAME=buster
> ID=raspbian
> ID_LIKE=debian
> HOME_URL="http://www.raspbian.org/"
> SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
> BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
> pi@soundbarPi4:~/rpi-audio-receiver-debian-10 $

**Comment by nicokaiser** [comment]
Yes, Buster may be less and less supported, since Bullseye has been released (over a year ago).
