### ISSUE TITLE
Bluetooth Pin Instructions seem to be outdated

### ISSUE THREAD

**Issue by stefansal** [nicokaiser/rpi-audio-receiver#148]
This refers to the [wiki entry here](https://github.com/nicokaiser/rpi-audio-receiver/wiki/Bluetooth-PIN)

I was trying to set up a PIN for the Bluetooth connection. However, the instructions in the wiki seem not to work anymore. (I think there has been a change since the switch to PulseAudio?) 
Are there new instructions on how to set up a PIN?

**Comment by nicokaiser** [comment]
I tried to set up a PIN for Bluetooth, but the only way I was successful was with SSP mode and without a PIN. And, as always, with a USB Bluetooth dongle, do not waste your time with the internal Bluetooth module.
