### ISSUE TITLE
RPI Stretch - Need to turn on Bluetooth discovery

### ISSUE THREAD

**Issue by thetonto** [nicokaiser/rpi-audio-receiver#15]
Have just done a fresh install on Raspberry PI W with 2018-11-13-raspbian-stretch-lite.img.

Also did a  rpi-update

All services came up but the unit was not discoverable.  Used 
bluetoothctl
power on
discovery on

Now it is all working.  Done a few reboots to confirm and all is fine.  Can't quite work out if this is semi permanent setting? 

Tempted now to give this a go on Buster

**Comment by nicokaiser** [comment]
I'll try to upgrade the scripts to Buster, and I'll review how Bluetooth discovery works (and how to make it permanent).

**Comment by nicokaiser** [comment]
Can you try again if this works? Should be fixed with Raspbian Buster and #24.
