### ISSUE TITLE
support for headphone with Mic

### ISSUE THREAD

**Issue by FireflyJar** [nicokaiser/rpi-audio-receiver#152]
this is to be label:"help wanted" 

I am in need of a device to connect my Cochlear (CI) / hearing aids to PC.   The CI can connect to Cell phone for hands free operation (using CI as headphone and Mic)   I am looking for a way to connect to PC  for gaming.   but Bluetooth adapters that can be purchased only works as headphones.  I can't seem to find anything that supports the Microphone. 
If not possible with rpi, then anyone knows another way?  TIA

**Comment by nicokaiser** [comment]
This seems a bit off-topic here: this project is about audio playback via Bluetooth (so the Bluetooth device is seen as a headphone from the playing device).
Getting audio _from_ the Bluetooth device requires a different mode of operation, but I do not have any experience in this. In theory, all USB Bluetooth adapters should support this (if the hearing aids announce themselves as headset), so you could try if a different headset (e.g. a cheap Bluetooth headset) works with the adapter. The operating system should handle Bluetooth headsets as microphone and output device (although most headset device switch to a different mode so the audio quality is much worse and more aimed towards speech than anything else).
