### ISSUE TITLE
Use sudo only in the scripts instead of the invocation

### ISSUE THREAD

**Issue by Slackadays** [nicokaiser/rpi-audio-receiver#153]
I think something that would make this project even awesome-r is if the `sudo ./install.sh` was replaced with just `./install.sh` and instead `sudo` gets used when it's needed within the scripts themselves. The reason for this is because not only does it look more trustworthy to new users, but it also acts as insurance in case some numbskull adds something of their own to the script that they don't know runs as root. The downside is that `sudo` will appear a lot in the scripts, but that only happens once.

**Comment by nicokaiser** [comment]
Sounds good. That way downloading and building of the Shairport Sync libraries could also happen as user, and only installation (`make install`) will be run with sudo.
