### ISSUE TITLE
bluetooth volume not controllable

### ISSUE THREAD

**Issue by belafonte** [nicokaiser/rpi-audio-receiver#155]
Hello hello,

just installed everything from the script.
So far everything works well.

The only thing that does not work is controlling the volume via bluetooth.
I'am using a usb bluetooth dongle and disabled the internal bluetooth module via: dtoverlay=pi3-disable-bt.
Not sure if that is correct though.

Any ideas how to solve this?

edit: and just out of curiosity, would it be possible somehow to output the audio as mono, when it is transmitted via bluetooth?

**Comment by doquanghuyit** [comment]
Did you solved this issues ? I'm facing this problem too

**Comment by sborn** [comment]
Try disabling Bluetooth using this more recent guide:

https://di-marco.net/blog/it/2020-04-18-tips-disabling_bluetooth_on_raspberry_pi/

**Comment by belafonte** [comment]
Cool thanks, will try it out!
