### ISSUE TITLE
Shairport Sync AirPlay 2 not installed due to missing ltmain.sh

### ISSUE THREAD

**Issue by Manuel5cc** [nicokaiser/rpi-audio-receiver#157]
While following the normal install process, this step fails because can't find ltmain.sh and it stops the whole setup.

**Comment by nicokaiser** [comment]
Could you try to rename `install.sh` to something else and run it?

**Comment by Manuel5cc** [comment]
I tried renaming it to `test.sh` and it looks lie it works!

**Comment by nicokaiser** [comment]
Fixed with #163
