### ISSUE TITLE
Device is Not Discoverable

### ISSUE THREAD

**Issue by pinsharp** [nicokaiser/rpi-audio-receiver#16]
Device Is not Discoverable RPI3 Model B... On Board Bluetooth.....

Used this Technique 
bluetoothctl
power on
discovery on
it kind of worked...
But Not discoverable After Reboot...

All Updated/Upgrade...etc.....Tried On a Cleaning again the OS too....

Still Don't Know the Error

**Comment by nicokaiser** [comment]
Can you try if this works with the newest version? Especially the changes in https://github.com/nicokaiser/rpi-audio-receiver/commit/44f34798e9d44ad12396c9aa3a204b1d1e76fd20 should make the device discoverable (And simple-pairable) on every reboot.
