### ISSUE TITLE
Not an issue. Feature request: Choose pulse audio or pipewire

### ISSUE THREAD

**Issue by karagir** [nicokaiser/rpi-audio-receiver#160]
Thank you tons for making RPi bluetooth audio receiver set-up a breeze!
Now with Bookworm out, how about a new version where we can choose between pulse audio or pipewire?
Thanks again in advance!!

**Comment by nicokaiser** [comment]
With Bookworm, it's even better because it includes BlueALSA again, so we can scrap PulseAudio and PipeWire and use only ALSA again. I'd like to reduce the complexity a bit...
