### ISSUE TITLE
move Uninstallation up in the README

### ISSUE THREAD

**Issue by lolie145** [nicokaiser/rpi-audio-receiver#167]
i didn't read all the way through (my own fault). And now i installed it without knowing it couldn't be uninstalled. a waring before the install step would be appreciated.

**Comment by nicokaiser** [comment]
I’ll consider this. Although this should be common sense to not just blindly execute scripts without fully understanding what they do…

**Comment by Siekerenterprises** [comment]
Hi
I am attempting to install you project and keep getting the error "Unsupported OS: Raspberry Pi OS 12 (bookworm) is required.
I imaged and loaded both the lite and the full, with the same result.
Am I missing something.

**Comment by nicokaiser** [comment]
Could you retry with the current version?

**Comment by Siekerenterprises** [comment]
Thanks for the reply, I will give it a try
