### ISSUE TITLE
Pair and disable

### ISSUE THREAD

**Issue by TGWC** [nicokaiser/rpi-audio-receiver#17]
How to connect the pair to a button in RP3, so no one cannot pair unless they press the button? For BT and for AirPlay ?

**Comment by nicokaiser** [comment]
That sounds like a great idea! 

This project does this, but the pairing itself is done in a very different way there, and I'd prefert to stick with Debian standards, e.g. systemd and maybe triggerhappyd.

https://circuitdigest.com/microcontroller-projects/diy-raspberry-pi-bluetooth-speaker
