### ISSUE TITLE
Only 1 BT connection at a time

### ISSUE THREAD

**Issue by TGWC** [nicokaiser/rpi-audio-receiver#18]
How to limit to one BT connection at a time?  Also, when pairing a BT Android, it asked for permission on the RP3, how to make this automatically ?

**Comment by nicokaiser** [comment]
What do you mean by „asked for permissive on the RP3“? These scripts actually make Raspbian accept all Bluetooth connections.

One way could be to disable the bluetooth-agent service (and thus, reject further pairing requests) while a device is connected.
