### ISSUE TITLE
no bt device shown on iphone

### ISSUE THREAD

**Issue by Goeste** [nicokaiser/rpi-audio-receiver#2]
Hi, I wanted to just use the bluetooth script, but no device shows up on my iphone when trying to find it. I can conect via ssh and bluetoothctl, but this should be prevented by udev i guess...

best regards,
goeste

**Comment by nicokaiser** [comment]
Is this still an issue? Much has been improved in Raspbian during the last year, so probably this is fixed?

**Comment by sumpfi82** [comment]
Yes it is still an issue! :(

**Comment by nicokaiser** [comment]
Could you check the output of `sudo hciconfig`? It should say `UP RUNNING PSCAN ISCAN` somewhere. If not, you might need to execute

```
hciconfig hci0 piscan
hciconfig hci0 sspmode 1
`
``

to set the Bluetooth system in the right state.

**Comment by sumpfi82** [comment]
Cool! It works! :)

**Comment by nicokaiser** [comment]
Great! Can you try to restart you Pi to see if this is persistent? It should be (unless you modified the filesystem to be read-only, in which case you might need to make it writable again, restart the `bluetooth` service, and do these steps), but I'm not sure...

**Comment by sumpfi82** [comment]
Yes, it seems to work even after reboot...
