### ISSUE TITLE
Bluetooth can't connect

### ISSUE THREAD

**Issue by c0rv0s** [nicokaiser/rpi-audio-receiver#22]
The raspberry pi shows up as a bluetooth audio device on my phone and laptop but when i try to connect, it tries for a second and then says "Couldn't connect"
Using Raspberry Pi 2 Model B v1.1 running 2019-07-10-raspbian-buster

**Comment by nopejs** [comment]
That's because auto-trust doesn't work per default atm. You can manually trust new devices using bluetoothctl.

**Comment by Blackbeard25** [comment]
this is what i had to do for my pi3
https://github.com/nicokaiser/rpi-audio-receiver/issues/23

**Comment by nicokaiser** [comment]
Can you try again? This should be fixed by #24.
