### ISSUE TITLE
Enable HifiBerry script only works for specific model of DAC

### ISSUE THREAD

**Issue by MattCost** [nicokaiser/rpi-audio-receiver#34]
HifiBerry makes several models now.
Updated instructions are here. https://www.hifiberry.com/docs/software/configuring-linux-3-18-x/

enable-hifiberry.sh script will only work for the first group of models listed in the Hifi Berry Instructions, other models require a different value in the  /boot/config.txt  line.

**Comment by nicokaiser** [comment]
Thanks for the suggestion. I modified the installer to allow to choose which overlay is being used. I may add a better selection with the proper board names in the future...
