### ISSUE TITLE
How to uninstall?

### ISSUE THREAD

**Issue by adas4190** [nicokaiser/rpi-audio-receiver#39]
how to unistall pls?

**Comment by nicokaiser** [comment]
There is no (elegant) way to uninstall this.

The purpose of this scripts is to convert a freshly installed, clean, Raspbian image to a simple audio receiver, so it is neither meant to be uninstalled, nor meant to be installed over a highly customized installation.

You can, however, have a look at the scripts and see what they do and try to revert this...
