### ISSUE TITLE
Equalizer for Audio Output

### ISSUE THREAD

**Issue by NaServas** [nicokaiser/rpi-audio-receiver#43]
Hello Nico,

I tried to add an equalizer to my system like described in this page: https://www.hifiberry.com/docs/software/guide-adding-equalization-using-alsaeq/

I was able to install the equalizer  and to use it, but unfortunately it doesn't affect the sound output.

Do you know if it is possible to add an equalizer on this system?
Or do I have to do further changes in /etc/asound.conf?

Greetings

Na Servas

**Comment by nicokaiser** [comment]
Unfortunately I do not have any experience with adding an equalizer to ALSA. This project is intended to provide a very simple starting point to individual setups, so I guess an equalizer is a bit out of scope here...
