### ISSUE TITLE
Suport for audioquest dragonfly dac

### ISSUE THREAD

**Issue by astra404** [nicokaiser/rpi-audio-receiver#45]
How should I make Dragonfly dac as main audio output?
Hardvare:
Raspberry pi zero 
Usb otg adapter

**Comment by nicokaiser** [comment]
I'm sorry this repository is not about DAC hardware. It assumes that you already got the audio setup working. You can try to add `dtparam=audio=off` to your `/boot/config.txt`, this disables the internal audio device and thus makes external devices the default (given they are set up correctly).
