### ISSUE TITLE
bluetooth 5.0 ?

### ISSUE THREAD

**Issue by kiai72** [nicokaiser/rpi-audio-receiver#46]
Hello,

i know you recommended buying a BT 4.0 USB adapter. 
I thought it might be a good idea to take teh newest standard: BT 5.0.
But obviously it wasn't a good idea, since it does not work.

these are the specs: https://launchstudio.bluetooth.com/ListingDetails/75270
when i do 'bluetoothctl list' it does not even show me the BT-controller.

so do i have any chance to get this to work ?

**Comment by nicokaiser** [comment]
Hello @kiai72! This depends if the device is supported by Raspbian / Debian 10. You can check if it's recognized at all using `usb-devices`, but I'm not sure how to proceed from there if it is not initialized automatically. Maybe here is some information about this: https://askubuntu.com/questions/1205962/bluetooth-dongle-problem
