### ISSUE TITLE
Change output device

### ISSUE THREAD

**Issue by aratar-orome** [nicokaiser/rpi-audio-receiver#49]
Hello Nico,

I want to define the output sound card by my one where the bluetooth stream is forwarded. In my case I dont want to playback the bluealsa sound on the default alsa device. How can I change this?

Best regards,
Andreas

**Comment by nicokaiser** [comment]
Hello @aratar-orome! This can be done by modifying the ALSA configuration, the software installed by this script will just use the default ALSA output device.

Some pointers may be on this page: https://www.raspberrypi.org/forums/viewtopic.php?t=35698
