### ISSUE TITLE
install-startup-sound.sh missing/redundant

### ISSUE THREAD

**Issue by jaquoh** [nicokaiser/rpi-audio-receiver#53]
Hey,
I love the project! I just installed it via `install.sh` and it failed after installing the snapcast client as it could not find `./install-startup-sound.sh`.
I looked into your `install.sh` and it contains `sudo ./install-startup-sound.sh`, but the repository does not. So either the `install-startup-sound.sh` is missing in the repo or you forgot to remove it from the `install.sh` script.

No big deal, but should be fixed.

Many thanks!

**Comment by nicokaiser** [comment]
Thanks for pointing out, shoud be fixed now!
