### ISSUE TITLE
Bluetooth udev script to disable WiFi isn’t working

### ISSUE THREAD

**Issue by rhealey-uk** [nicokaiser/rpi-audio-receiver#6]
Hi.

I have followed the setup instructions and installed everything.  This is on Pi Zero W running Raspbian Stretch Lite.

Everything is working as it should be except the Bluetooth udev script to disable the WiFi whilst using Bluetooth connection.  I do have the audio dropouts so i am hoping someone can let me know what to check to find out why this isn’t working.

I am not a Linux expert but I will try and follow your advice to get this working.

Thanks
Rick

**Comment by arjunmenon** [comment]
Because he has [commented the line](https://github.com/nicokaiser/rpi-audio-receiver/blob/master/install-bluetooth.sh#L187) which controls turning off the wifi

You can manually do it.

**Comment by nicokaiser** [comment]
As @arjunmenon said. This is commented out, because my recommended setup is to use an external Bluetooth device (because the internal Bluetooth in the Pi Zero / Pi 3+ is not very reliable for audio streaming).
