### ISSUE TITLE
Plexamp?

### ISSUE THREAD

**Issue by ashenkin** [nicokaiser/rpi-audio-receiver#61]
Thanks for this great guide.  Wondering if you think plexamp could work well with this?  I’ve tried running plexamp in rpi players before, but it tends to compete with the audio channel, so either it grabs it, or airplay grabs it.  Any thoughts?  Many thanks...

**Comment by nicokaiser** [comment]
Sorry, I do not have any experience with plexamp.

Your description sounds a bit like the audio device may be occupied by another process. This could be fixed by using `dmix` in your ALSA configuration, an example for the HiFiBerry DACs is in `enable-hifiberry.sh`.
