### ISSUE TITLE
Use Raspotify instead of Spotifyd

### ISSUE THREAD

**Issue by JasonLG1979** [nicokaiser/rpi-audio-receiver#65]
[Raspotify](https://github.com/dtcooper/raspotify) is a super thin wrapper around librespot (what Spotifyd is based on), basically just a unit file that runs librespot as a daemon and a config file. It works out of the box on every version of the Raspberry Pi and I would guess be lighter then Spotifyd. It would also reduce your Spotify install script to:

```curl -sL https://dtcooper.github.io/raspotify/install.sh | sh```

You loose nothing since you don't use any of the extra features that Spotifyd provides over librespot.

**Comment by nicokaiser** [comment]
Wow, I totally missed this! Thanks for the suggestion, it looks great, I'm currently testing it and it seems to work much better than Spotifyd.
