### ISSUE TITLE
Add a wiki

### ISSUE THREAD

**Issue by JasonLG1979** [nicokaiser/rpi-audio-receiver#74]
It would be helpful to add a wiki with the locations to the different services config files along with example configs and the default values of those configs.

Basic audio troubleshooting would also be helpful.

**Comment by nicokaiser** [comment]
I like the idea!

**Comment by JasonLG1979** [comment]
> I like the idea!

You have to enable the wiki before anyone can add anything to it.

**Comment by JasonLG1979** [comment]
You also have to allow other people to edit it otherwise I can't add anything to it.

**Comment by nicokaiser** [comment]
You are right. I changed the permissions to public, let's see if this works (I'd like to keep an eye on the structure and the contents of the Wiki and not let it become an all-purpose-"Audio on Linux" wiki, but maybe it works).

**Comment by JasonLG1979** [comment]
> I'd like to keep an eye on the structure and the contents of the Wiki and not let it become an all-purpose-"Audio on Linux" wiki, but maybe it works

Well this repo has the potential to enable several different audio services. Because of that my general idea was to take them though the steps of creating a functional default output. A default that will take pretty much anything you'd throw at it and make noise. ALSA is ALSA regardless of distro so 99.9% of it would be by venture of that fact "all purpose".

**Comment by JasonLG1979** [comment]
There I added an audio configuration page. I think it's pretty simple but again by general necessity it's pretty "all purpose" in that generally speaking it's pretty distro agnostic. If you don't like it ofc feel free to delete and/or edit it.
