### ISSUE TITLE
Not installing snapcast causes installation stop early

### ISSUE THREAD

**Issue by jens4Dev** [nicokaiser/rpi-audio-receiver#78]
When you don't want to install snapcast, the install.sh script stops working because the  install-snapcast-client.sh ends with exit 1 in that case.
Like other script it need to end with 0:
`if [[ ! "$REPLY" =~ ^(yes|y|Y)$ ]]; then exit 0; fi`

**Comment by nicokaiser** [comment]
Nice catch, thanks!
