### ISSUE TITLE
Booting Pi in read-only mode

### ISSUE THREAD

**Issue by arjunmenon** [nicokaiser/rpi-audio-receiver#8]
Hi
After installation, I will be following [this guide](https://learn.adafruit.com/read-only-raspberry-pi/) to setup Pi in read-only mode, so that it can behave as a common hardware - ie, no need to follow proper shutdown procedure.

Will this affect the audio-receiver in anywy?

**Comment by nicokaiser** [comment]
The `enable-read-only.sh` script does exactly this – execute the script mentioned in the guide and do some modifications that prevent some warnings caused by this.
