### ISSUE TITLE
Pin Prevent unauthorized Bluetooth connection with rpi-audio-receiver device

### ISSUE THREAD

**Issue by Nacionarte** [nicokaiser/rpi-audio-receiver#83]
HI,
It is possible to do it?
Pin protect the pairing process with the rip audio receiver so unauthorized devices can't connect to it.

**Comment by nicokaiser** [comment]
I tried to use a PIN for pairing Bluetooth, however this requires switching to an old an less secure pairing mode that does not seem to work at all with iOS devices. See https://github.com/nicokaiser/rpi-audio-receiver/issues/48#issuecomment-686666414

You could try to change the files like in this commit: https://github.com/nicokaiser/rpi-audio-receiver/commit/3678cf9f0640b80e4a1083482ed58f31a8dcff14 but as I said, it simply did not work for me...
