### ISSUE TITLE
feature-proposal: reuse raspi-config overlay fs to protect SD from corruption during hard poweroff

### ISSUE THREAD

**Issue by rriemann** [nicokaiser/rpi-audio-receiver#85]
Dear all,

I just read about one option in `raspi-config`: Performance Option P3 Overlay File System (Enable/Disable read-only file system)

Wouldn't this be more convenient than the permanent switch of `enable-read-only.sh`?

**Comment by nicokaiser** [comment]
Nice catch! I did not know that `raspi-config` added this option! I'll try what it does exactly, but I guess you are right, this might be a better option than using an own script (which also only works on Raspberry Pi OS).

**Comment by nicokaiser** [comment]
The old read-only script was removed now, `raspi-config` should be used for read-only mode.
