### ISSUE TITLE
raspotify linear volume

### ISSUE THREAD

**Issue by ante4711** [nicokaiser/rpi-audio-receiver#87]
Minor update needed in raspotify configuration /etc/default/raspotify
  --linear-volume
  should be updated to 
  --volume-ctrl linear

(as https://github.com/dtcooper/raspotify/commit/64d44d8c39068beaa9706cd76c6b965718587830 etc indicates )

And thanks for this project, got my old speakers up and running in notime :)

**Comment by janek** [comment]
@nicokaiser please consider reopening this, the issue is still there and it means raspotify is broken out of the box
