### ISSUE TITLE
Feature: Sync multiple Pi's

### ISSUE THREAD

**Issue by jbonnett92** [nicokaiser/rpi-audio-receiver#9]
Hi,
Is it possible we can a new feature to this? I was thinking something like Sonos where you can have multiple Pi's and sync the sound to each.

Jamie

**Comment by nicokaiser** [comment]
Unfortunately, AirPlay 2 (which does support proper multi-speaker setups) is not (yet) reverse engineered, so currently the only way is to use iTunes and (multiple) AirPlay 1 (via shairport-sync) devices.

There is something called [Snapcast](badaix/snapcast), but I did not have the time to try it. Maybe integrating a Snapcast client (!) would be a no-brainer, but you would still need a server (and this project is about building the receiver-part of the setup).

**Comment by jbonnett92** [comment]
@nicokaiser That link doesn't exist for me.

**Comment by nicokaiser** [comment]
> @nicokaiser That link doesn't exist for me.

Sorry, the link was wrong, I fixed it in the comment.
