### ISSUE TITLE
How to disable Bluetooth Audio and play System audio from output when needed/desired

### ISSUE THREAD

**Issue by Shabinder** [nicokaiser/rpi-audio-receiver#91]
This Scripts works great!
Just one thing...
How to go back to play System Audio from Speakers when needed.

**Comment by Shabinder** [comment]
Seems Audio works if we change output source for vlc to digital in vlc prefrence but chromium sound still not working!

Seems like Chromium doesnt work well with bluealsa...
Help plz

**Comment by nicokaiser** [comment]
I think I did not quite understand what you are trying to do. Would you like to play system audio (like notification sounds) from your local speakers, but VLC sound via Bluetooth on the Raspberry Pi? (This would require some configuration on the client and depends on your setup...)

**Comment by Shabinder** [comment]
Never Mind I got it working, thanks for this project
