### ISSUE TITLE
Dietpi

### ISSUE THREAD

**Issue by jkiddo** [nicokaiser/rpi-audio-receiver#93]
Any plans for supporting dietpi?

**Comment by nicokaiser** [comment]
No sorry, no plans currently. DietPi is a distribution with a quite special package management that supports many hardware platforms. I cannot support multiple platforms: the scope of this project is to provide a very basic step to transform a dedicated Raspberry Pi and a standard Raspberry Pi OS installation into an audio receiver while staying as close to Debian standards as possible.

I considered using Buildroot for this, however this would involve vast amounts of customization to run Bluetooth, AirPlay and Spotify Connect at all, and providing good support for all Raspberry Pi models and especially Audio HATs is not easy (and, most importantly: there is already HiFiBerry OS which does exactly this and works great).
