### ISSUE TITLE
Bluetooth Authentification

### ISSUE THREAD

**Issue by SaschaMuehl** [nicokaiser/rpi-audio-receiver#96]
Thank you again Nico for the cool skript. 

Is the a way to set up a bluetooth authentification like "0000" or "1234"?

**Comment by nicokaiser** [comment]
I added a Wiki page with some pointers on how Bluetooth PIN support *might* be possible. However as this does not work at all with iOS devices, this is disabled by default and this script uses the more secure SSP mode instead.

https://github.com/nicokaiser/rpi-audio-receiver/wiki/Bluetooth-PIN
