### ISSUE TITLE
different audio streams playing at the same time

### ISSUE THREAD

**Issue by merccooper** [nicokaiser/rpi-audio-receiver#97]
This happens if i connect snapcast and airplay, both of the files can be heard at the same time.

Is it possible to prioritise the streams so when playing from airplay snapcast will pause?

I saw something similar here (https://github.com/StalkerSVR/snapcast-multiroom) but i am to dumb to implement it :/

**Comment by nicokaiser** [comment]
I think [HiFiBerry OS](https://github.com/hifiberry/hifiberry-os/) tries to achieve this, however this requires massive work and modifications on all players. This is beyond the scope of this little project, I'm sorry...
